### ISSUE TITLE
small fixes to .desktop url shortcut files

### ISSUE THREAD

**Issue by nestukh** [gyng/save-in#54]
First: I'd like to thank devs for the awesome work.
Now: low priority request: the famous SaveLink firefox extension saves url .desktop files with few more lines than Save-In. Lines useful for linux file managers. 
It would be nice to improve the internal text from (example): 

[Desktop Entry]
Encoding=UTF-8
Type=Link
Title=https://github.com/gyng/save-in/issues/new
URL=https://github.com/gyng/save-in/issues/new

to:

[Desktop Entry]
Encoding=UTF-8
Icon=text-html
Type=Link
Name=New Issue · gyng/save-in
URL=https://github.com/gyng/save-in/issues/new
[InternetShortcut]
URL=https://github.com/gyng/save-in/issues/new

The second one is directly from a SaveLink-generated desktop file (I've added the slash in the Name field). 
It's pretty much it.
Thank you for listening.

**Comment by gyng** [comment]
Thanks for this, it's really helpful. I'll look into adding this.

**Comment by nestukh** [comment]
Thank you and the others for this extension. Saving links in shortcut files is SO useful for me and for a subset of power users. I understand that the new APIs aren't as good as the old ones, but I hope to completely replace SaveLink with Save-In, in time.

**Comment by gyng** [comment]
Added in v2.4.0. Please reopen if it doesn't work as expected.

**Comment by nestukh** [comment]
Hello, almost perfect: Name and Title fields should have the webpage title, not the url address (causes problems on filenames on desktop folder).

Also: sometimes, instead of webpage title it saves the file with a "new tab.desktop" filename, especially when changing webpage under the same tab. A quick fix is go to another tab then switch it back, the correct filename is therefore shown. It is a new github issue? It's still a fix for shorturl files.

I'm using Firefox ESR 64bit 52.6.0 on Debian stable (default choice for this linux distribution), with KDE.
You could test it downloading an ISO image from http://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/current-live/amd64/iso-hybrid/ (i.e. the amd64-kde+nonfree.iso one) and running it in a VirtualBox machine, if it can provide any help or if you don't have a linux box for debugging.

**Comment by gyng** [comment]
It tries to get the page title, but falls back to the URL if it fails. Might be an issue with the tab activation detection.

**Comment by gyng** [comment]
I pushed a quick fix for the shortcut content in 2.4.1, but I haven't been able to replicate the `new tab.desktop` issue. Is there a particular site/link that reliably causes it? I will need to try it out on ESR when I get access to another machine.

**Comment by nestukh** [comment]
shourtcuts are now practically perfect, new tab issue is still present, but switching tab back-and-forth is an easy-enough fix for me.


In any case, further information: it's on every site, e.g. https://news.ycombinator.com 

After your message, I've thought that was combination of various other ad-block/customization extensions working together, but I started a fresh profile, installed save-in and the issue is still present.

Without the "open a file dialog when saving" option, it saves a "New Tab.desktop" file in default download folder whitout asking; with that option checked, it saves it whitout asking as well, even if I push 'cancel' instead of 'save'. 
Doing this multiple times, it results in multiple "New Tab(n).desktop" empty files.

Instead, first "New Tab.desktop" has this content:
[Desktop Entry]
Encoding=UTF-8
Icon=text-html
Type=Link
Name=New Tab
Title=New Tab
URL=https://news.ycombinator.com
[InternetShortcut]
URL=https://news.ycombinator.com

**Comment by nestukh** [comment]
save-in works perfectly in firefox 60 esr! No need to switch tabs! So I'm closing the issue :)
Thank you!!
